// <auto-generated />
using System;
using CatalogMicroservice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatalogMicroservice.Database.AttentionMode", b =>
                {
                    b.Property<int>("AttentionModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttentionModeId");

                    b.ToTable("AttentionModes");

                    b.HasData(
                        new
                        {
                            AttentionModeId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(4851),
                            CreationUser = "ADMIN01",
                            Description = "Presencial"
                        },
                        new
                        {
                            AttentionModeId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(6049),
                            CreationUser = "ADMIN01",
                            Description = "Virtual"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.BackofficeUser", b =>
                {
                    b.Property<string>("BUserCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BUserCode");

                    b.ToTable("BackofficeUsers");

                    b.HasData(
                        new
                        {
                            BUserCode = "b20200601",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(923),
                            CreationUser = "ADMIN01",
                            Email = "b20200601@upc.edu.pe",
                            FirstName = "Mármol",
                            LastName = "Coloma",
                            Names = "Roberto André"
                        },
                        new
                        {
                            BUserCode = "s20200601",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(2299),
                            CreationUser = "ADMIN01",
                            Email = "s20200601@upc.edu.pe",
                            FirstName = "Chumacero",
                            LastName = "Cruz",
                            Names = "Luigui"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.BiblioSchedule", b =>
                {
                    b.Property<string>("BUserCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BUserCode", "CampusId", "StartTime", "EndTime");

                    b.HasIndex("CampusId");

                    b.ToTable("BiblioSchedule");

                    b.HasData(
                        new
                        {
                            BUserCode = "b20200601",
                            CampusId = 1,
                            StartTime = new DateTime(2020, 7, 5, 16, 55, 2, 984, DateTimeKind.Local).AddTicks(578),
                            EndTime = new DateTime(2020, 7, 5, 20, 55, 2, 984, DateTimeKind.Local).AddTicks(1272),
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 984, DateTimeKind.Local).AddTicks(2032),
                            CreationUser = "ADMIN01"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampusId");

                    b.ToTable("Campus");

                    b.HasData(
                        new
                        {
                            CampusId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(7793),
                            CreationUser = "ADMIN01",
                            Description = "Campus Monterrico"
                        },
                        new
                        {
                            CampusId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(8888),
                            CreationUser = "ADMIN01",
                            Description = "Campus Villa"
                        },
                        new
                        {
                            CampusId = 3,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(8915),
                            CreationUser = "ADMIN01",
                            Description = "Campus San Miguel"
                        },
                        new
                        {
                            CampusId = 4,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(8915),
                            CreationUser = "ADMIN01",
                            Description = "Campus San Isidro"
                        },
                        new
                        {
                            CampusId = 5,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 981, DateTimeKind.Local).AddTicks(8918),
                            CreationUser = "ADMIN01",
                            Description = "Campus Virtual"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.KnowledgeBase", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InquiriesQuantity")
                        .HasColumnType("int");

                    b.Property<int>("NegativeCalification")
                        .HasColumnType("int");

                    b.Property<int>("Pinned")
                        .HasColumnType("int");

                    b.Property<int>("PositiveCalification")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("KnowledgeBase");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "Respuesta para citación de figuras y tablas",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(3923),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Cómo citar figuras o tablas?",
                            ServiceTypeId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "Respuesta para el parafraseo",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5157),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Cómo es el parafraseo?",
                            ServiceTypeId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "Respuesta para las notas a pie de página",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5181),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Qué son las notas a pie de página? ¿Cómo se usan?",
                            ServiceTypeId = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "Respuesta para reporte de coincidencias de Safe Assign",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5184),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "Reporte de coincidencias de Safe Assign",
                            ServiceTypeId = 2
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "Respuesta para búsqueda por temas",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5187),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "Búsqueda por temas",
                            ServiceTypeId = 3
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer = "Respuesta para búsqueda de revistas en cuartiles",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5190),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "Búsqueda de revistas en cuartiles",
                            ServiceTypeId = 3
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer = "Respuesta para revistas indexadas por disciplina",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5193),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "Revistas indexadas por disciplina",
                            ServiceTypeId = 3
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer = "Respuesta para instalar import to Mendeley",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5196),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Cómo instalar import to Mendeley?",
                            ServiceTypeId = 4
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer = "Respuesta para instalar el plugin de word en Mendeley",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5196),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Cómo instalar el plugin de word en Mendeley?",
                            ServiceTypeId = 4
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer = "Respuesta para búsqueda de artículos científicos",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5199),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Dónde puedo buscar artículos científicos?",
                            ServiceTypeId = 5
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer = "Respuesta para ruta de plantillas de acuerdo a la carrera",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5202),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿Dónde puedo encontrar plantillas de acuerdo a mi carrera?",
                            ServiceTypeId = 6
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer = "Respuesta para análisis bibliométrico?",
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(5205),
                            CreationUser = "ADMIN01",
                            InquiriesQuantity = 0,
                            NegativeCalification = 0,
                            Pinned = 0,
                            PositiveCalification = 0,
                            Question = "¿En qué se basa el análisis bibliométrico?",
                            ServiceTypeId = 7
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(4215),
                            CreationUser = "ADMIN01",
                            Description = "Bibliotecólogo"
                        },
                        new
                        {
                            RoleId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(5256),
                            CreationUser = "ADMIN01",
                            Description = "Supervisor"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceRequest", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttentionModeId")
                        .HasColumnType("int");

                    b.Property<string>("BUserCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Career")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UPCCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("AttentionModeId");

                    b.HasIndex("BUserCode");

                    b.HasIndex("CampusId");

                    b.HasIndex("ServiceStatusId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceRequestDetail", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestSequence")
                        .HasColumnType("int");

                    b.Property<string>("AttentionDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceStatusId")
                        .HasColumnType("int");

                    b.HasKey("ServiceRequestId", "ServiceRequestSequence");

                    b.HasIndex("ServiceStatusId");

                    b.ToTable("ServiceRequestDetail");
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceStatus", b =>
                {
                    b.Property<int>("ServiceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceStatusId");

                    b.ToTable("ServiceStatus");

                    b.HasData(
                        new
                        {
                            ServiceStatusId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(6892),
                            CreationUser = "ADMIN01",
                            Description = "Registrada"
                        },
                        new
                        {
                            ServiceStatusId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(7912),
                            CreationUser = "ADMIN01",
                            Description = "Asignada"
                        },
                        new
                        {
                            ServiceStatusId = 3,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(7936),
                            CreationUser = "ADMIN01",
                            Description = "En atención"
                        },
                        new
                        {
                            ServiceStatusId = 4,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 982, DateTimeKind.Local).AddTicks(7936),
                            CreationUser = "ADMIN01",
                            Description = "Cerrada"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 977, DateTimeKind.Local).AddTicks(3629),
                            CreationUser = "ADMIN01",
                            Description = "Normas de citación y referencias"
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9447),
                            CreationUser = "ADMIN01",
                            Description = "Test de Similitud"
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9495),
                            CreationUser = "ADMIN01",
                            Description = "Búsqueda de información"
                        },
                        new
                        {
                            ServiceTypeId = 4,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9498),
                            CreationUser = "ADMIN01",
                            Description = "Gestores de referencias (Mendeley)"
                        },
                        new
                        {
                            ServiceTypeId = 5,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9501),
                            CreationUser = "ADMIN01",
                            Description = "Búsqueda de artículos científicos"
                        },
                        new
                        {
                            ServiceTypeId = 6,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9501),
                            CreationUser = "ADMIN01",
                            Description = "Plantilla de Tesis y Trabajo de investigación"
                        },
                        new
                        {
                            ServiceTypeId = 7,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9504),
                            CreationUser = "ADMIN01",
                            Description = "Análisis bibliométrico"
                        },
                        new
                        {
                            ServiceTypeId = 8,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 978, DateTimeKind.Local).AddTicks(9507),
                            CreationUser = "ADMIN01",
                            Description = "Asesoría"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.UserRoles", b =>
                {
                    b.Property<string>("BUserCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BUserCode", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            BUserCode = "b20200601",
                            RoleId = 1,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(7657),
                            CreationUser = "ADMIN01"
                        },
                        new
                        {
                            BUserCode = "s20200601",
                            RoleId = 2,
                            CreationDate = new DateTime(2020, 7, 5, 16, 55, 2, 983, DateTimeKind.Local).AddTicks(8879),
                            CreationUser = "ADMIN01"
                        });
                });

            modelBuilder.Entity("CatalogMicroservice.Database.BiblioSchedule", b =>
                {
                    b.HasOne("CatalogMicroservice.Database.BackofficeUser", "BackofficeUser")
                        .WithMany("BiblioSchedule")
                        .HasForeignKey("BUserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogMicroservice.Database.Campus", "Campus")
                        .WithMany("BiblioSchedule")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogMicroservice.Database.KnowledgeBase", b =>
                {
                    b.HasOne("CatalogMicroservice.Database.ServiceType", "ServiceType")
                        .WithMany("KnowledgeBase")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceRequest", b =>
                {
                    b.HasOne("CatalogMicroservice.Database.AttentionMode", "AttentionMode")
                        .WithMany("ServiceRequest")
                        .HasForeignKey("AttentionModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogMicroservice.Database.BackofficeUser", "BackofficeUser")
                        .WithMany("ServiceRequest")
                        .HasForeignKey("BUserCode");

                    b.HasOne("CatalogMicroservice.Database.Campus", "Campus")
                        .WithMany("ServiceRequest")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogMicroservice.Database.ServiceStatus", "ServiceStatus")
                        .WithMany("ServiceRequest")
                        .HasForeignKey("ServiceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogMicroservice.Database.ServiceType", "ServiceType")
                        .WithMany("ServiceRequest")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogMicroservice.Database.ServiceRequestDetail", b =>
                {
                    b.HasOne("CatalogMicroservice.Database.ServiceRequest", "ServiceRequest")
                        .WithMany("ServiceRequestDetail")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogMicroservice.Database.ServiceStatus", "ServiceStatus")
                        .WithMany("ServiceRequestDetail")
                        .HasForeignKey("ServiceStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogMicroservice.Database.UserRoles", b =>
                {
                    b.HasOne("CatalogMicroservice.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
