// <auto-generated />
using System;
using AuthenticationMicroservice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticationMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200603021713_User01")]
    partial class User01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Career")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPCCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Career = "Ingeniería de Sistemas - EPE",
                            CreationDate = new DateTime(2020, 6, 2, 21, 17, 13, 202, DateTimeKind.Local).AddTicks(3384),
                            CreationUser = "ADMIN01",
                            Email = "U201524462@upc.edu.pe",
                            FirstName = "Acero",
                            LastName = "Soria",
                            Names = "Dany Daniel",
                            Password = "Password1",
                            Phone = "999888555",
                            UPCCode = "U201524462"
                        },
                        new
                        {
                            UserId = 2,
                            Career = "Ingeniería de Sistemas - EPE",
                            CreationDate = new DateTime(2020, 6, 2, 21, 17, 13, 202, DateTimeKind.Local).AddTicks(3875),
                            CreationUser = "ADMIN01",
                            Email = "U201524476@upc.edu.pe",
                            FirstName = "Canales",
                            LastName = "Tacilla",
                            Names = "Luis Brayan",
                            Password = "Password2",
                            Phone = "999555888",
                            UPCCode = "U201524476"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
